name: grateful_notes
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bridgestate:
    git:
        url: https://github.com/onuohasilver/bridges.git
        ref: master
  flutter_screenutil: ^5.6.0
  animate_do: ^3.0.2
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  equatable: ^2.0.5
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.4
  bot_toast: ^4.0.3
  lottie: ^1.4.2
  logger: ^1.1.0
  animated_text_kit: ^4.2.2
  cloudinary_public: ^0.20.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
  # - assets/animations/
  - assets/images/
  - assets/icons/
  # - .env
