// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8AoR1lDaaw0cmo8TCQQ01woOJhD3ccf4',
    appId: '1:915947266058:web:4c6834d90e3e539cd73ff3',
    messagingSenderId: '915947266058',
    projectId: 'grateful-notes',
    authDomain: 'grateful-notes.firebaseapp.com',
    storageBucket: 'grateful-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXyQXQ_wWuHkb7WsW-nyY1hFcnv0UeHuQ',
    appId: '1:915947266058:android:19a8830d07c2d4a1d73ff3',
    messagingSenderId: '915947266058',
    projectId: 'grateful-notes',
    storageBucket: 'grateful-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaAYvQjuH2b4Ee49kt6M1cfESQy3OUEDE',
    appId: '1:915947266058:ios:99db42ce3e2a5ea2d73ff3',
    messagingSenderId: '915947266058',
    projectId: 'grateful-notes',
    storageBucket: 'grateful-notes.appspot.com',
    iosClientId: '915947266058-7pfqpbt92och1oc326oop4spls1rdgo4.apps.googleusercontent.com',
    iosBundleId: 'com.obinna.gratefulNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaAYvQjuH2b4Ee49kt6M1cfESQy3OUEDE',
    appId: '1:915947266058:ios:87e17105a7423eeed73ff3',
    messagingSenderId: '915947266058',
    projectId: 'grateful-notes',
    storageBucket: 'grateful-notes.appspot.com',
    iosClientId: '915947266058-2vs20bhjj7jjl63ii8t56craojeals2v.apps.googleusercontent.com',
    iosBundleId: 'com.example.gratefulNotes',
  );
}
